[project]
name = "navdata_sql"
version = "0.1.0"
dependencies = [
]

[project.optional-dependencies]
dev = [
    "ipython"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

pythonpath = [ "navdata_sql" ]
testpaths = [ "test" ]
